import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowUpRight } from 'lucide-react';
const pages:Record<string,{label:string;tag:string;title:string;intro:string}>={
utbildning:{label:'Utbildning',tag:'FÖR SKOLOR, ARBETSPLATSER OCH OFFENTLIG SEKTOR',title:'Kunskap för bättre möten.',intro:'Förstå mer av de människor ni möter. Minaret erbjuder fortbildning om islam och muslimers vardag i Sverige, med fokus på frågor som berör er verksamhet.'},
bocker:{label:'Böcker',tag:'MINARET FÖRLAG',title:'Plats för fördjupning.',intro:'Böcker ger oss tid att stanna upp, förstå sammanhang och upptäcka nya perspektiv. Minarets utgivning växer ur vårt folkbildningsuppdrag.'},
kurser:{label:'Kurser',tag:'FÖR DIG SOM VILL LÄRA MER',title:'Lärande som får ta tid.',intro:'Fördjupa din kunskap om islam och dess plats i vardagen. Våra planerade kurser förenar kunskap, reflektion och samtal i en svensk kontext.'},
kunskapsbank:{label:'Kunskapsbank',tag:'KUNSKAP SOM ÄR TILL FÖR ATT DELAS',title:'En öppen dörr till kunskap.',intro:'Här bygger vi en samlingsplats för artiklar, guider och faktablad om islam och muslimers vardag i Sverige. Tillgänglig kunskap för nyfikna människor.'},
'om-minaret':{label:'Om Minaret',tag:'KUNSKAP · GEMENSKAP · UTVECKLING',title:'Förståelse börjar med kunskap.',intro:'Minaret är en svensk folkbildningsaktör med fokus på islam i en svensk kontext. Vi vill göra kvalitativ kunskap tillgänglig och bidra till ömsesidig förståelse.'},
kontakt:{label:'Kontakt',tag:'ETT SAMTAL KAN VARA EN BÖRJAN',title:'Låt oss lära känna er.',intro:'Vill ni utveckla kunskapen i er organisation, veta mer om Minaret eller utforska ett samarbete? Vi vill gärna höra vilka frågor som är viktiga för er.'}
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=pages[slug];return {title:p?.label,description:p?.intro}}
const training=[['Islam och muslimer i Sverige','En grund för att förstå tro, praktik och muslimers varierande erfarenheter i en svensk samhällskontext.'],['Att möta muslimska elever och familjer','Perspektiv och kunskap som stöd för dialog i skolan och möten med elever och vårdnadshavare.'],['Islam på arbetsplatsen','Vardagsnära frågor om bland annat Ramadan, högtider och mötet mellan religion och arbetsliv.']];
function Cards({items}:{items:string[][]}){return <div className="content-grid">{items.map(([title,text])=><article className="content-card" key={title}><h2>{title}</h2><p>{text}</p></article>)}</div>}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=pages[slug];if(!p)notFound();return <main id="main"><section className={'page-hero books-hero hero-'+slug}>{<div className="books-hero-art" aria-hidden="true"><span className="book-leaf leaf-back"/><span className="book-leaf leaf-middle"/><span className="book-leaf leaf-front"/><span className="book-spark">✳</span></div>}<div className="container"><div className="breadcrumb"><Link href="/">Hem</Link><span>/</span><span>{p.label}</span></div><span className="eyebrow">{p.tag}</span><h1>{p.title}</h1><p className="intro">{p.intro}</p>{slug==='utbildning'&&<Link href="/kontakt" className="button primary">Prata utbildning med oss <ArrowUpRight size={18}/></Link>}</div></section><section className="container page-section">
{slug==='utbildning'&&<><span className="eyebrow">EXEMPEL PÅ UTBILDNINGSOMRÅDEN</span><Cards items={training}/><div className="detail-copy"><h2>Utifrån er verksamhets frågor.</h2><p>En föreläsning kan skapa en gemensam grund. En workshop ger utrymme för frågor och reflektion. Ett längre utbildningsupplägg kan ge möjlighet till fördjupning.</p><p>Vi utgår från er målgrupp, era kunskapsbehov och de situationer ni möter. Innehåll, format och omfattning tas fram i dialog med er.</p><Link href="/kontakt" className="text-link">Berätta om era behov <ArrowUpRight size={18}/></Link></div></>}
{slug==='bocker'&&<><div className="empty-panel"><span className="status">Utgivning under arbete</span><h2>De första böckerna tar form.</h2><p>Vi arbetar med vår första utgivning. Här kommer du att kunna läsa om böckerna, upptäcka deras innehåll och hitta information om hur de kan beställas när de är tillgängliga.</p></div><div className="detail-copy"><h2>Kunskap att bära med sig.</h2><p>Vår planerade utgivning rymmer islamisk tro och praktik, historia och frågor som berör vardagen i Sverige. Böcker och studiematerial ska hjälpa läsaren att förstå, reflektera och fördjupa sig.</p><p>Ett av våra långsiktiga kunskapsprojekt handlar om profeten Muhammeds liv, Sirah. Arbetet kan ta form i tematiska böcker och material för vidare studier.</p></div></>}
{slug==='kurser'&&<><div className="empty-panel"><span className="status">Kursutbud under utveckling</span><h2>Mer kunskap. Fler samtal.</h2><p>Vi förbereder kurser för dig som vill fördjupa din förståelse av islam och livet i en svensk kontext. Kursbeskrivningar, upplägg och datum presenteras här när de är klara.</p></div><div className="detail-copy"><h2>Frågor som berör livet.</h2><p>Tro och praktik, familj och relationer, identitet och samhällsdeltagande är exempel på teman som ryms i vårt folkbildningsuppdrag.</p><p>Med ett pedagogiskt upplägg vill vi ge plats för både kunskap och egen reflektion.</p><Link href="/utbildning" className="text-link">Söker du utbildning för en organisation? <ArrowUpRight size={18}/></Link></div></>}
{slug==='kunskapsbank'&&<><span className="status">Kunskapsbanken byggs upp</span><Cards items={[
['Islam i en svensk kontext','Planerade artiklar om tro, praktik och hur kunskapen möter vardagslivet i Sverige.'],['Skola och arbetsliv','Planerade guider och faktablad som ger stöd för förståelse på arbetsplatser och i skolor.'],['Identitet och gemenskap','Planerade texter om familj, tillhörighet och samhällsdeltagande.']]}/><div className="detail-copy"><h2>Begripligt, relevant och öppet.</h2><p>Kunskapsbanken ska erbjuda olika vägar in i ett ämne: korta svar, förklarande guider och fördjupande texter. Material publiceras successivt efter redaktionell granskning.</p><p>De första artiklarna är ännu inte publicerade. Under tiden kan du läsa mer om vårt uppdrag och våra utbildningsområden.</p><Link href="/om-minaret" className="text-link">Om Minarets folkbildning <ArrowUpRight size={18}/></Link></div></>}
{slug==='om-minaret'&&<><div className="detail-copy"><span className="eyebrow">VÅRT UPPDRAG</span><h2>Kunskap som bygger broar.</h2><p>Vi vill stärka muslimers kunskap om islam, med särskilt fokus på vardagsliv, familj, arbetsliv och samhälle i Sverige. Samtidigt vill vi hjälpa skolor, kommuner, arbetsgivare och allmänheten att bättre förstå islam och muslimers liv.</p><p>De två perspektiven hör ihop. När kunskap blir tillgänglig får människor bättre förutsättningar att förstå sig själva och varandra.</p><h2>Folkbildning i flera former.</h2><p>Vi arbetar genom utbildningar, böcker, kurser och digitalt kunskapsmaterial. Formen varierar, men syftet är detsamma: att göra kunskap begriplig, relevant och användbar.</p><h2>Tradition möter samhällskontext.</h2><p>Minarets utgångspunkt är kombinationen av islamisk kunskapstradition, förståelse för det svenska samhället och pedagogik. Vi vill ge plats åt nyfikenhet, genomtänkta frågor och konstruktiva samtal.</p><h2>Ett långsiktigt arbete.</h2><p>Vår ambition är att bygga en varaktig kunskapsinstitution och en naturlig plats att vända sig till för lärande om islam i en svensk kontext.</p><h2>Människan bakom initiativet.</h2><p>Niklas Yosuf är grundare av Minaret. Initiativet förenar arbete med innehåll, författarskap och föreläsningar med ambitionen att bygga en långsiktig folkbildningsverksamhet.</p><Link href="/kontakt" className="button primary">Ta kontakt med Minaret <ArrowUpRight size={18}/></Link></div></>}
{slug==='kontakt'&&<div className="contact-layout"><div><h2>Ert behov är utgångspunkten.</h2><p>Inför en utbildningsförfrågan får ni gärna beskriva vilka ni är, vilka som ska delta och vilka frågor ni vill fördjupa er i. Berätta också om ni har önskemål om format eller tidpunkt.</p><div className="note-box"><strong>Kontaktuppgifter kommer inom kort.</strong><br/>Kontaktvägen öppnas inför lanseringen. Det går ännu inte att skicka en förfrågan via webbplatsen.</div></div><div className="contact-options"><div className="contact-option"><span className="eyebrow">UTBILDNING</span><h2>För er organisation</h2><p>Fortbildning, föreläsningar och workshops med utgångspunkt i er verksamhets frågor.</p></div><div className="contact-option"><span className="eyebrow">SAMARBETE OCH ÖVRIGA FRÅGOR</span><h2>För ett gemensamt lärande</h2><p>Frågor om Minaret, böcker, kurser eller möjligheten att bidra till folkbildningen.</p></div></div></div>}
</section></main>}
